name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tfbackendrg: 'terraform-shared'
  tfbackendsa: 'mkoutfsharedsa'
  tfbackendcontainer: 'tfstates'
  tfbackendkey: 'skedda-chellenge.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendAzureRmResourceGroupName: '${tfbackendrg}'
            backendAzureRmStorageAccountName: '${tfbackendsa}'
            backendAzureRmContainerName: '${tfbackendcontainer}'
            backendAzureRmKey: '${tfbackendkey}'
        - task: TerraformTaskV4@4
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            env:
              ARM_ACCESS_KEY: $(STORAGEACCOUNTKEY)
              ARM_CLIENT_ID: 242fe934-0122-4b1e-9bd6-2d46533774a1
              ARM_TENANT_ID: b514d0ef-f17c-4989-93cd-b11010f1130f
              ARM_SUBSCRIPTION_ID: 88c7e449-6ac7-4e8e-838d-5702a085812c
              ARM_CLIENT_SECRET: $(SPSECRET)
            inputs:
              provider: 'azurerm'
              command: 'init'
              # backendServiceArm: 'AzureConnection'
              backendAzureRmResourceGroupName: '${tfbackendrg}'
              backendAzureRmStorageAccountName: '${tfbackendsa}'
              backendAzureRmContainerName: '${tfbackendcontainer}'
              backendAzureRmKey: '${tfbackendkey}'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'

