name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tfbackendrg: 'terraform-shared'
  tfbackendsa: 'mkoutfsharedsa'
  tfbackendcontainer: 'tfstates'
  tfbackendkey: 'skedda-chellenge.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'AzureRMConnection'
            backendAzureRmResourceGroupName: '$(tfbackendrg)'
            backendAzureRmStorageAccountName: '$(tfbackendsa)'
            backendAzureRmContainerName: '$(tfbackendcontainer)'
            backendAzureRmKey: '$(tfbackendkey)'
            workingDirectory: '$(System.DefaultWorkingDirectory)/deployments/terraform'
            
        - task: TerraformTaskV4@4
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init 
            env:
              ARM_ACCESS_KEY: $(STORAGEACCOUNTKEY)
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AzureRMConnection'
              backendAzureRmResourceGroupName: '$(tfbackendrg)'
              backendAzureRmStorageAccountName: '$(tfbackendsa)'
              backendAzureRmContainerName: '$(tfbackendcontainer)'
              backendAzureRmKey: '$(tfbackendkey)'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/deployments/terraform'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/deployments/terraform'

