name: "Deploy dotnet package"

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet build aspnetcoreapp.csproj -c Release
  displayName: 'dotnetBuild'
  workingDirectory: 'application/aspnetcoreapp/'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  displayName: deployWebApp
  inputs:
    azureSubscription: 'AzureRMConnection'
    appType: 'webAppLinux'
    appName: 'skedda-challenge-app-service'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|7.0'