name: "Deploy dotnet package"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureWebApp@1
  displayName: deployWebApp
  inputs:
    azureSubscription: 'AzureRMConnection'
    appType: 'webAppLinux'
    appName: 'skedda-challenge-app-service'
    package: 'aspnetcoreapp.zip'
    runtimeStack: 'DOTNETCORE|7.0'